sonarqube:
  url: "https://sonarqube.example.com"
  token: "your-sonarqube-token"

defectdojo:
  url: "https://defectdojo.example.com"
  token: "your-defectdojo-token"

slack:
  webhook_url: "https://hooks.slack.com/services/your/webhook"
